import type { Metadata } from "next"
import { LegalPage } from "@/components/legal-page"
import { business } from "@/lib/products"

export const metadata: Metadata = {
  title: "Privacy Policy | Swadam Foods",
  description: "Privacy Policy explaining how Swadam Foods collects, uses, shares and protects personal data.",
}

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro={`This Privacy Policy explains how ${business.name} ("Swadam Foods", "we", "our", "us") collects and processes personal data when you visit https://swadamfoods.eu.cc, place an order, make a payment, contact us, or otherwise interact with our services.`}
      sections={[
        {
          heading: "What Information We Collect",
          paragraphs: [
            "Depending on how you use the website, we may collect your name, phone number, email address, delivery address, pincode, order details, customer-service communications, payment-related references, and information you voluntarily provide to us.",
            "We may also automatically receive limited technical information such as IP address, browser/device information, pages visited, approximate timing of visits, and other information generated by your interaction with the website.",
          ],
        },
        {
          heading: "Why We Use Your Information",
          paragraphs: [
            "We use personal data to process and fulfil orders, communicate about orders and deliveries, process or reconcile payments, provide customer support, respond to complaints, prevent fraud and abuse, maintain security, improve the website, understand website usage, comply with legal obligations, and perform other purposes disclosed at or before collection.",
            "We do not require an account for ordinary checkout. Where information is optional, you may choose not to provide it, but some services cannot be provided without information that is necessary for that service, such as delivery details for an order.",
          ],
        },
        {
          heading: "Payments & Payment Providers",
          paragraphs: [
            "When you choose online payment, payment processing may be handled by PhonePe and, where used as an alternative payment provider, Razorpay. These providers may process personal and transaction data necessary to authenticate and complete the payment. Their own privacy notices and terms also apply to the processing they perform.",
            "Swadam Foods does not ask customers to send or disclose card PINs, CVVs, UPI PINs, OTPs, net-banking passwords, wallet credentials, or similar authentication secrets to us. We keep payment references and transaction status needed for reconciliation, customer support, accounting and legal requirements.",
          ],
        },
        {
          heading: "Service Providers & Sharing",
          paragraphs: [
            "We may share relevant information with payment providers, logistics or delivery providers, website hosting and infrastructure providers, analytics providers, customer-support or communication providers, professional advisers, and other processors who help us operate the business. We share only information reasonably necessary for the relevant purpose.",
            "We may also disclose information to government authorities, regulators, courts, law-enforcement agencies, or other authorised parties when required by law or reasonably necessary to protect rights, investigate fraud, enforce our terms, or protect customers and the public.",
          ],
        },
        {
          heading: "Analytics & Cookies",
          paragraphs: [
            "We use Google Analytics and similar technologies to understand how visitors use the website, measure performance, and improve the customer experience. These tools may use cookies or related identifiers and may collect technical and usage information according to their own policies.",
            "You can control cookies through your browser or device settings. Blocking some cookies or scripts may affect portions of the website, but essential checkout functionality should remain dependent only on information required to provide the service.",
          ],
        },
        {
          heading: "Security",
          paragraphs: [
            "We use reasonable technical and organisational measures appropriate to the nature of the personal data we process. Payment secrets and gateway credentials are kept server-side and are not intended to be exposed through the customer-facing website. However, no internet transmission or storage system can be guaranteed to be completely secure.",
          ],
        },
        {
          heading: "Retention",
          paragraphs: [
            "We retain personal data for as long as reasonably necessary for the purposes described in this policy, including order fulfilment, customer support, accounting, dispute handling, fraud prevention and compliance with applicable law. When information is no longer required, we may securely delete or anonymise it subject to legal and operational requirements.",
          ],
        },
        {
          heading: "Your Choices & Data Rights",
          paragraphs: [
            `You may contact ${business.email} to request access to, correction or updating of your personal data, or to request deletion where permitted by applicable law. Certain information may need to be retained where required for legal obligations, pending orders, disputes, fraud prevention or other lawful purposes.`,
            "Where applicable under Indian data-protection law, we will provide the rights and complaint mechanisms required by the legal framework in force at the relevant time. Consent, where relied upon, may be withdrawn through the method provided to you, although withdrawal may affect our ability to provide services that require the relevant information.",
          ],
        },
        {
          heading: "Children",
          paragraphs: [
            "Our website is a general retail website and is not directed specifically at children. We do not knowingly seek to collect personal data from children except where permitted through a parent, guardian or applicable legal process.",
          ],
        },
        {
          heading: "Third-Party Websites",
          paragraphs: [
            "The website may link to third-party services, including payment or social-media platforms. We are not responsible for the privacy practices of third-party websites, and you should review their own policies before submitting information to them.",
          ],
        },
        {
          heading: "Applicable Data Protection Law",
          paragraphs: [
            "This policy is intended to be read with applicable Indian data-protection and privacy laws, including the Digital Personal Data Protection Act, 2023 and applicable rules and notifications as they come into force and apply to our processing activities. We will update this policy when material changes in law or our processing practices require it.",
          ],
        },
        {
          heading: "Grievance & Contact",
          paragraphs: [
            `Designated grievance contact: Vidya Ajit Dandekar, Owner / Authorised Representative. Address: ${business.address}. Email: ${business.email}. Phone: ${business.phoneDisplay}. Customer-support hours: Monday–Friday, 9:00 AM–6:00 PM IST.`,
          ],
        },
      ]}
    />
  )
}
