import type { Metadata } from "next"
import { LegalPage } from "@/components/legal-page"
import { business } from "@/lib/products"

export const metadata: Metadata = {
  title: "Terms & Conditions | Swadam Foods",
  description: "Terms and Conditions governing use of the Swadam Foods website and purchase of products under Indian Law.",
}

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      updatedAt="9 September 2026"
      intro={`This document is an electronic record published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and the Consumer Protection (E-Commerce) Rules, 2020 under the Information Technology Act, 2000 and the Consumer Protection Act, 2019. Being an electronic record generated by a computer system, it does not require any physical or digital signatures.`}
      sections={[
        {
          heading: "1. About the Platform & Entity Details",
          paragraphs: [
            `This website https://swadamfoods.eu.cc (hereinafter referred to as the "Platform") is owned and operated by ${business.name}, a sole proprietorship firm registered in Maharashtra, India (Proprietorship: ${business.proprietor}), having its principal place of business at ${business.address}.`,
            `Food Safety and Standards Authority of India (FSSAI) License Number: ${business.fssai}.`,
            `Ministry of Micro, Small and Medium Enterprises (MSME) UDYAM Registration: ${business.udyam}.`,
            `For the purposes of these Terms of Use, wherever the context so requires, "you", "your", or "user" shall mean any natural or legal person who browses, accesses, or places an order on the Platform. "We", "us", or "our" refers to ${business.name}.`,
          ],
        },
        {
          heading: "2. Acceptance of Terms & Eligibility",
          paragraphs: [
            "By accessing, browsing, or transacting on this Platform, you expressly acknowledge and agree to be bound by these Terms & Conditions, along with our Privacy Policy, Refund & Cancellation Policy, Return Policy, Shipping Policy, and Payment Policy, each of which is incorporated herein by reference.",
            "Eligibility to Contract: You represent and warrant that you are at least 18 years of age and fully competent to enter into a legally binding agreement under the Indian Contract Act, 1872. If you are under 18 years of age, you may browse the Platform only under the supervision and with the consent of a parent or legal guardian.",
          ],
        },
        {
          heading: "3. Product Information, Quality & FSSAI Standards",
          paragraphs: [
            `All food products offered on the Platform (including Patal Poha Chivda, Instant Kanda Poha Premix, and Instant Upma Premix) are prepared, packed, and labelled in strict adherence to the Food Safety and Standards Act, 2006 (FSSA 2006) and the regulations framed thereunder by FSSAI.`,
            `In compliance with the Legal Metrology (Packaged Commodities) Rules, 2011, each product displayed on the Platform explicitly indicates its net weight, Maximum Retail Price (MRP inclusive of all statutory taxes), list of ingredients, nutritional information, allergen advisory (e.g., presence of peanuts), batch number, manufacturing date, and "Best Before" date on the packaging. Country of Origin for all products is India.`,
            "Photographs and visual depictions on the Platform are for illustrative purposes. While we take every effort to ensure accurate representation, actual product packaging appearance may vary slightly due to continuous packaging refinements.",
          ],
        },
        {
          heading: "4. Pricing, Taxes & Orders",
          paragraphs: [
            "All prices displayed on the Platform are stated in Indian National Rupees (INR / ₹) and are inclusive of all applicable statutory taxes (Goods and Services Tax - GST where applicable). Delivery charges, if applicable outside standard free-delivery tiers, are clearly calculated and displayed before you complete checkout.",
            "An order placed on the Platform constitutes an offer to purchase. A legally binding contract of sale is formed when we receive payment confirmation from our authorized payment aggregator and transmit an order confirmation with your unique Order ID via our Platform, SMS, or WhatsApp.",
            "We reserve the right to decline or cancel any order prior to dispatch in the event of unforeseen product stock-out, inability to service your pincode, pricing or typographical errors, or suspicious fraudulent activity. In any such instance where an order is cancelled by us, any payment collected will be refunded 100% to your original payment source without deductions.",
          ],
        },
        {
          heading: "5. Payments & Security",
          paragraphs: [
            "Payments on the Platform are processed through Reserve Bank of India (RBI) authorized Payment Aggregators (such as PhonePe and/or Razorpay). Accepted instruments include UPI (PhonePe, Google Pay, Paytm, BHIM), Debit/Credit Cards (Visa, Mastercard, RuPay), and NetBanking.",
            "We strictly comply with RBI directives on Card-on-File Tokenization (CoFT). Swadam Foods does not store, capture, or access your sensitive financial secrets (card CVVs, full card numbers, UPI PINs, or NetBanking passwords). All online transactions require mandatory Multi-Factor Authentication (OTP or UPI MPIN) administered directly by your issuing bank and the payment gateway.",
          ],
        },
        {
          heading: "6. User Conduct & Acceptable Use",
          paragraphs: [
            "You agree not to use the Platform for any purpose that is unlawful, defamatory, harassing, or in violation of any applicable Indian central, state, or municipal law.",
            "You agree not to probe, scan, test the vulnerability of, or attempt to compromise the security or rate-limiting measures of our website or APIs. Any unauthorized attempt to inject malicious scripts, launch denial-of-service attacks, reverse engineer software bundles, or fraudulently manipulate transaction values will result in immediate termination of access and reporting to law enforcement authorities under the Information Technology Act, 2000.",
          ],
        },
        {
          heading: "7. Intellectual Property Rights",
          paragraphs: [
            `All intellectual property on the Platform—including brand names, trade dress, recipes, textual content, product photography, UI graphics, logos, and software code—is the proprietary property of ${business.name} and ${business.proprietor} or licensed to us. No portion of this Platform may be reproduced, duplicated, republished, or commercially exploited without our prior written consent.`,
          ],
        },
        {
          heading: "8. Limitation of Liability & Force Majeure",
          paragraphs: [
            "To the fullest extent permitted by applicable Indian law, Swadam Foods shall not be liable for any indirect, punitive, incidental, or consequential damages resulting from the use or inability to use our services or products.",
            "Neither party shall be held liable for any delay or failure to perform its contractual obligations if such failure is caused by a Force Majeure event beyond reasonable control, including acts of God, extreme weather, floods, epidemics/pandemics, governmental restrictions, civil unrest, transport/courier strikes, or widespread telecommunications/internet failures.",
          ],
        },
        {
          heading: "9. Customer Grievance Redressal Mechanism",
          paragraphs: [
            `In accordance with Rule 4(4) of the Consumer Protection (E-Commerce) Rules, 2020 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the designated Grievance Officer details are as follows:`,
            `Name & Designation: ${business.grievanceOfficer}, Grievance Officer\nEntity: ${business.name} (Proprietorship: ${business.proprietor})\nAddress: ${business.address}\nEmail: ${business.email}\nPhone / WhatsApp: ${business.phoneDisplay}\nWorking Hours: Monday to Saturday, 09:30 AM to 06:30 PM IST`,
            "Statutory Redressal Timelines: We acknowledge receipt of any consumer complaint within forty-eight (48) hours of receipt and provide redressal or resolution of the complaint within thirty (30) days from the date of its receipt.",
          ],
        },
        {
          heading: "10. Governing Law & Dispute Resolution",
          paragraphs: [
            "These Terms of Use, their interpretation, and any claims or disputes arising out of or related to your use of the Platform or purchase of products shall be governed exclusively by the substantive laws of the Republic of India.",
            "Subject to the dispute resolution mechanism, the competent courts having jurisdiction over Pune, Maharashtra, India shall have exclusive jurisdiction to settle any disputes arising under these Terms.",
          ],
        },
      ]}
    />
  )
}
